-- =============================
-- TABLAS
-- =============================

CREATE TABLE CLIENTE_Q (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100)
);

CREATE TABLE PRODUCTO_D (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER
);

CREATE TABLE INFO_CLIENTE (
    ID NUMBER PRIMARY KEY,
    CLIENTE_ID NUMBER,
    DIRECCION VARCHAR2(150),
    TELEFONO VARCHAR2(50)
);

CREATE TABLE EMPRESA_VENTA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CIUDAD VARCHAR2(100)
);

COMMIT;

--? Inserción de Datos (36 registros por tabla)
BEGIN
    FOR i IN 1..36 LOOP
        INSERT INTO CLIENTE_Q VALUES (i, 'Cliente ' || i, 'cliente' || i || '@mail.com');
        INSERT INTO PRODUCTO_D VALUES (i, 'Producto ' || i, i * 1000);
        INSERT INTO INFO_CLIENTE VALUES (i, i, 'Direccion ' || i, '30000000' || i);
        INSERT INTO EMPRESA_VENTA VALUES (i, 'Empresa ' || i, 'Ciudad ' || i);
    END LOOP;
END;
/

COMMIT;

SELECT * FROM CLIENTE_Q c
INNER JOIN INFO_CLIENTE ic ON c.ID = ic.CLIENTE_ID
INNER JOIN PRODUCTO_D p ON c.ID = p.ID
INNER JOIN EMPRESA_VENTA e ON c.ID = e.ID;