-- =============================
-- TABLAS
-- =============================

CREATE TABLE CLIENTE_Q (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100)
);

CREATE TABLE PRODUCTO_D (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER
);

CREATE TABLE INFO_CLIENTE (
    ID NUMBER PRIMARY KEY,
    CLIENTE_ID NUMBER,
    DIRECCION VARCHAR2(150),
    TELEFONO VARCHAR2(50)
);

CREATE TABLE EMPRESA_VENTA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CIUDAD VARCHAR2(100)
);

COMMIT;